### ISSUE TITLE
'Magic request methods require a URI and optional options array'  Exception Being thrown

### ISSUE THREAD

**Issue by nicklee1990** [casperbakker/guzzle-oauth#1]
I keep seeing this error:

'InvalidArgumentException' with message 'Magic request methods require a URI and optional options array' in /home/vagrant/Code/errand/vendor/guzzlehttp/guzzle/src/Client.php:80

Have you seen this/any ideas? My composer has dev-master for this library and ~6.0 for Guzzle

My code:

        $stack = HandlerStack::create();

        $client = new Guzzle([
            'base_url' => 'https://api.twitter.com/1.1/',
            'defaults' => ['auth' => 'oauth'],
            'handler' => $stack
        ]);

        $oauth = new Oauth1([
            'consumer_key' => env('TWITTER_CONSUMER_KEY'),
            'consumer_secret' => env('TWITTER_CONSUMER_SECRET'),
            'token' => env('TWITTER_TOKEN'),
            'token_secret' => env('TWITTER_TOKEN_SECRET')
        ]);

        $client->getEmitter()->attach($oauth); // This line throw the exception
        ....

**Comment by casperbakker** [comment]
Hi @nicklee1990,

This is not the right repository, take a look at https://github.com/casperbakker/oauth-subscriber

That repo works with Guzzle 6 and with Twitter's oAuth. Also re-read that readme, cause you do not need that getEmitter and the 'defaults' => [] not anymore.
